# Generated by Django 5.2.7 on 2026-03-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
