# Generated by Django 5.2.7 on 2026-03-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "doctor",
                    models.CharField(
                        choices=[
                            ("dr_sarah", "Dr. Sarah Ahmed - Pet Medicine Specialist"),
                            ("dr_rahim", "Dr. Rahim Chowdhury - Surgery Specialist"),
                            (
                                "dr_nabila",
                                "Dr. Nabila Islam - Skin & Allergy Specialist",
                            ),
                            (
                                "dr_tanvir",
                                "Dr. Tanvir Hossain - Bird & Exotic Pet Specialist",
                            ),
                            ("dr_farzana", "Dr. Farzana Kabir - Livestock Specialist"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
